### PR TITLE
[FRONT-92] Remove API Key service from profile page

### PR DESCRIPTION
**Pull request by juhah**
Remove API Key section from profile page & unused actions services for stream API keys.

### CODE REVIEW

**Comment by fonty1** [comment]
@juhah thanks for removing the docs mentions! I'll do the same on the `streamr-client` readme.

**Comment by juhah** [comment]
> thanks for removing the docs mentions! I'll do the same on the streamr-client readme.

@fonty1 Yeah, soon we'll need another pass on the docs, the functionality has changed at some points

**Review by tumppi — APPROVED** [review]
Nice! Good to get rid of code that is not needed 👍

**Review by mondoreale — APPROVED** [review]
Screen Shot 2020-10-15 at 4 45 39 PM

😳

This is good. It builds and works with no hiccups.

**Pull request merged**
