### PR TITLE
Disable community products in staging, fix stream selector styles

### PR DESCRIPTION
**Pull request by juhah**
Disable community products in staging. Also fixed the stream selector styles while editing. Everything (purchase, publish, unpublish, editing, etc) should work normally with the old components.

### CODE REVIEW

**Comment by fonty1** [comment]
Hmm, I removed `COMMUNITY_PRODUCTS=on` from my `.env` and the stream selector seemed to fail to pull in streams. No errors in the console. I will do a little more digging. Are you able to replicate that? When I put the variable back they appeared again.

Screenshot 2019-11-07 at 11 25 02
Screenshot 2019-11-07 at 11 22 05

**Comment by juhah** [comment]
@fonty1 No, works for with or without the flag 🤔

**Comment by fonty1** [comment]
> @fonty1 No, works for me with or without the flag 🤔

Ahh, very weird, it is the same behaviour for me in production.. so hmm, 🤷‍♂ 

When I click edit I see the streams, so that's odd.

**Comment by fonty1** [comment]
I think it might just be something we missed on the first version of the product creator then. The stream selector should be in edit mode on load, rather than in listing mode. 

Since this is going to be switched out, probs not a high priority to adjust.

**Pull request merged**
