### PR TITLE
[PLATFORM-1284] Improve change current wallet dialogue

### PR DESCRIPTION
**Pull request by juhah**
Desktop:
Screen Shot 2020-02-24 at 14 15 08

Mobile:
Screen Shot 2020-02-24 at 14 15 14

### CODE REVIEW

**Comment by mattatgit** [comment]
Actually mobile looks a fair bit different to the design too:

Screenshot 2020-02-25 09 14 27

**Comment by juhah** [comment]
Updated dialogs:

Screen Shot 2020-02-26 at 13 53 57
Screen Shot 2020-02-26 at 13 53 48

Mobile dialog height is now set for all steps. I updated also these mobile dialogs with margins around the icon:
Screen Shot 2020-02-26 at 13 54 09
Screen Shot 2020-02-26 at 13 54 14 
Screen Shot 2020-02-26 at 13 56 23

**Comment by mattatgit** [comment]
Thanks @juhah Re the desktop modal there, the thing that was a bit off was mainly the padding between the last line of text and the end of the dialogue background.

Screenshot 2020-02-27 09 22 49

Re the mobile ones, sorry for the hassle, i think they might need a bit more adjustment, they're a bit odd in huge amounts of space around the icon & almost none below the text. I'll look at it again today & get back to you.

**Comment by mattatgit** [comment]
@juhah 
Here's a pass on the mobile modals to improve vertical spacing consistency.

**Examples**
mobile_modals_examples

**Guide to vertical spacing for mobile**
mobile_modal_spacing_guide 

**Abstract link**
https://share.goabstract.com/26e36ab4-f391-45d2-b324-4659946057c3?mode=design&sha=37465ed85e4f00abf76f1cf82fc8b779288cb762

**All mobile modals, updated, on Abstract** 
https://share.goabstract.com/ce78fb23-6e4e-472b-9c8f-f677d490b757?mode=design&sha=37465ed85e4f00abf76f1cf82fc8b779288cb762

**Comment by juhah** [comment]
Updated the styles:
Screen Shot 2020-03-05 at 10 02 05
Screen Shot 2020-03-05 at 10 02 00
Screen Shot 2020-03-05 at 10 04 42
Screen Shot 2020-03-05 at 10 04 36
Screen Shot 2020-03-05 at 10 04 29

**Comment by mattatgit** [comment]
@juhah Looks good to me, though maybe the copy for Insufficient DAI could be brought in line with the copy for the other 2 ?

**Comment by juhah** [comment]
> Looks good to me, though maybe the copy for Insufficient DAI could be brought in line with the copy for the other 2

@mattatgit Good point - fixed in https://github.com/streamr-dev/streamr-platform/pull/902/commits/2b9dbde7fe22451aaf8996945557f11a32a3af39:

Screen Shot 2020-03-06 at 10 54 38

**Pull request merged**
