### PR TITLE
[PLATFORM-504] Module Search Panel minimising behavior

### PR DESCRIPTION
**Pull request by juhah**
I changed the minimising behaviour so that it expands if minimised and a search text is entered (instead of disabling). I also made the box smaller (max height) by default to what it is in the designs (352px). 

module-search-minimise

### CODE REVIEW

**Comment by mattatgit** [comment]
@juhah Looks better. Not sure where you're getting 352px width from the designs though, it has all been setup at 248px for a few months.

Search_module

https://share.goabstract.com/a81dcecd-f666-4ddc-9c53-c2550d1a15a7

**Comment by juhah** [comment]
@mattatgit Sorry, I meant the maximum height that it will stretch to is 352px when there are more results than we can show. Should we allow more?

**Comment by mattatgit** [comment]
@juhah Oh ok, cool, that sounds better. Re max limit - bit hard to say without trying it, so i'd say leave it as is for now & we'll test it.

**Comment by tumppi** [comment]
Oh, I noticed that if you resize the module search window and just click minimize toggle two times, it'll forget its height and resets to default.

**Comment by mattatgit** [comment]
@tumppi Yep we probably need a bit more sophisticated solution that keeps things compact for the search bar side but allows the browse side to be vertically expanded.

**Comment by mattatgit** [comment]
@mondoreale @tumppi 

> I've noticed that resizing a collapsed panel doesn't affect the collapse/expand button. Maybe it could change it to "expanded" state… 

Yep, i agree, if user re-expands the panel, the icon should change to reflect that.

**Comment by juhah** [comment]
> if user re-expands the panel, the icon should change to reflect that

Added toggling based on dragged size.

> if you resize the module search window and just click minimize toggle two times, it'll forget its height and resets to default

I left the minimised state unset because it should react to the result list size. We could improve it later by for example:
1) expand to full or match result list size if user hasn't dragged the window
2) If user has dragged the window, use it as the height

**Pull request merged**
