### PR TITLE
Add webpack-bundle-analyzer

### PR DESCRIPTION
**Pull request by mondoreale**
I'm working on async `zxcvbn` loading. It's going pretty well. 💃 I'd like to merge this little puppy first tho. I saw @fonty1 using it long time ago, thought it's kinda cool; why don't we use it?

It is useful to analyze both production and development bundles that's why it's included for both envs. You have to explicitly request it when running `npm run build` (via the optional `ANALYZE` env variable).

Example:
```
ANALYZE=1 NODE_ENV=production node --max_old_space_size=4096 ./node_modules/.bin/webpack
```

screenshot 2018-11-23 12 47 25

Thoughts?

### CODE REVIEW

**Comment by timoxley** [comment]
@mondoreale 👍 I wonder if we could somehow produce a bundle report in CI that can be printed into the PR. Unless these things are automated they tend to be forgotten.

Another option that produces a size diff is http://webpackmonitor.com/

**Comment by mondoreale** [comment]
@timoxley how would you want it to work? (1) You look it up in the actual CI build report or (2) see it here somewhere?

**Comment by timoxley** [comment]
@mondoreale wherever is easiest, reporting it a custom check's details link would be ideal. would also be good to report other stuff about the build e.g. the deployed PR url. Perhaps a github bot.

**Comment by mondoreale** [comment]
@Aapzu I'd like to skip the CI part for now. Your points are good though! I'll make sure the analyzer doesn't block anything; simply generate `dist/report.html` file. Please see bb19f6b for details. We can turn it into something more fancy down the road!

**Pull request merged**
