### PR TITLE
[PLATFORM-1370] Implement Create ETH account in Settings

### PR DESCRIPTION
**Pull request by juhah**
Implement Create ETH account in Settings

* Renamed "Ethereum identities" section to "Ethereum accounts", nav links as "ETH accounts" & "ETH canvas keys"
* Updated intro text, added bold text to "eth canvas keys" intro
* Added new button that allows creation of ETH accounts
* Renamed existing button to "Connect wallet"
* Added new flow for renaming account and copying private key

Screen Shot 2020-05-21 at 10 50 53

Design: https://share.goabstract.com/a15f9c4b-9fb2-40d7-a39a-a0e4fff5b774

Connect wallet
ezgif-2-1fa8814d7764

Create account
ezgif-2-4f1ad4c136a5

Eth key for canvas
ezgif-2-78cc53f9be1e

### CODE REVIEW

**Comment by juhah** [comment]
PR url: http://streamr-marketplace-pr-1462608929f4adb505ea8593a5943052d50f2f51.s3-website-eu-west-1.amazonaws.com

**Comment by mattatgit** [comment]
@juhah Looks like it all works as planned, looking good. I'd like to do a small update to the MM signature request modal, but otherwise, works for me.

Updated MM modal here
https://share.goabstract.com/492470bf-211d-41ff-b82c-50dde76bd351?mode=design&sha=22fda9a67b422eb66e3a86d23687ca30a90593e5

Screenshot 2020-05-22 11 28 04

One other thing, please check the ticket for the discussion about changing the intro text to something a bit more clear
https://streamr.atlassian.net/browse/PLATFORM-1370

**Comment by juhah** [comment]
> Looks good but we need to update the text, and ideally also the modal as mentioned.

Updated text:
Screen Shot 2020-05-24 at 9 00 06

Updated modal:
ezgif-2-168f863fa332

**Comment by mattatgit** [comment]
@juhah Looks pretty good. One thing: it's not good typographic form to end a line with a single word after a comma, so if we can force a line break in the first line of intro text after "smart contracts," it would read much better. ie

... smart contracts,
and signing data in streams. Connect your ...

**Comment by juhah** [comment]
Ok, updated the text:
Screen Shot 2020-05-24 at 12 12 42

**Comment by mattatgit** [comment]
If the third line of the intro starts with 

" and Marketplace ..."
ie the second line force breaks after "Core".
then no more requests from me, all good to go.

**Comment by juhah** [comment]
Yep, now like this:
Screen Shot 2020-05-24 at 13 42 12

**Pull request merged**
