### PR TITLE
[PLATFORM-1192] NPM Audit package version bumps

### PR DESCRIPTION
**Pull request by fonty1**
Closing #820 in favour of this fix inside the package lock. 

Worth keeping an eye on whether this fixes #822 - seems to work OK, locally at least.

I didn't update css-loader to the very latest because it requires a higher version of node than what we run in our build environments.

### CODE REVIEW

**Comment by mondoreale** [comment]
@fonty1 I'm fixing conflicts and rebasing this one in a minute, FYI.

**Comment by mondoreale** [comment]
Dropped package-lock changed in a80883cf30da3464d740366f6f27b6dc4935dc9b and bumped the file up in 972fbdf. @fonty1, ready for a merge?

**Comment by fonty1** [comment]
> Dropped package-lock changed in [a80883c](https://github.com/streamr-dev/streamr-platform/commit/a80883cf30da3464d740366f6f27b6dc4935dc9b) and bumped the file up in [972fbdf](https://github.com/streamr-dev/streamr-platform/commit/972fbdf658f95633d7458f9b67983738bae92c26). @fonty1, ready for a merge?

@mondoreale ah sorry I missed this, I needed to put out a fire. Let me just do a quick test locally, then it's good to go.

**Comment by fonty1** [comment]
Mergin 😎

**Pull request merged**
