### PR TITLE
[FRONT-149] Fix data union members graph

### PR DESCRIPTION
**Pull request by tumppi**
Use streamr-client Subscription to get stream data instead of HTTP API.

### CODE REVIEW

**Review by mondoreale — APPROVED** [review]
LGTM

I may be responsible for Travis failures in feature branches. I'll fix that shortly.

**Review by juhah — COMMENTED** [review]
I couldn't properly test this with many users but graph loads now 👍 the days selector behaves funny, though:

ezgif-2-c19a2ed940bf

**Comment by mondoreale** [comment]
#1118 will greenify CI build.

**Comment by mondoreale** [comment]
#1118 merged!

**Comment by tumppi** [comment]
Made some fixes here. Tested with Swash data and works ok now. The only thing that is weird that resends for that Swash joinPartStream stop on 20 Oct, so 90 days and especially 28 days graph look a bit weird. 7 days works perfectly so that resend problem is only occurring between 20 Oct and 31 Oct. Actually that is not probably a resend bug but just that there is no data for that part.

This code should be good to go. There's nothing we can do for that data.

**Review by juhah — APPROVED** [review]
> This code should be good to go. There's nothing we can do for that missing data.

Weird 🤔 might be good to file a backend issue about it, though

**Pull request merged**
