### PR TITLE
[PLATFORM-448] General Docs Design Feedback

### PR DESCRIPTION
**Pull request by fonty1**
Addressing this feedback:
https://paper.dropbox.com/doc/Docs-Feedback-yQoqzVgbdY4U3U4PsSDjE

PR URL:
https://d15scsxh0u1mht.cloudfront.net/docs

### CODE REVIEW

**Comment by fonty1** [comment]
Thanks Matt, round 2 review should be accessible within a couple hours and my comments are in the Paper doc.
There are caching irregularities on PR urls so they probably always need a hard refresh.

**Comment by fonty1** [comment]
@mattatgit yep, https://d2hp95cf1tto64.cloudfront.net/docs appears to have expired, so I'll send an update to rebuild and update this thread with a new URL. This build process takes a couple of hours.

**Comment by fonty1** [comment]
@mattatgit 
URL valid until ~29th March:
https://dxgk7zca3q5bf.cloudfront.net/docs

**Comment by mattatgit** [comment]
@fonty1 Thank you sir. Looking good to me — unless Saori finds anything else on her pass today, these look good to go in terms of design & layout.

**Pull request merged**
