### PR TITLE
[PLATFORM-1148] Fix unselectable dropdown in firefox

### PR DESCRIPTION
**Pull request by timoxley**
Chart range & port value select dropdowns were unselectable and closed immediately on click in Firefox.
This fixes that.

#### To Test

1. Open a canvas with a select dropdown port e.g. "unit" port in `Clock` or "window type" in the `Count` module.
2. Add a `Chart` module and note the "Range" dropdown in the chart body. 
3. Dropdowns should appear, and values should change if selected in Chrome, Safari & Firefox.

### CODE REVIEW

**Comment by mondoreale** [comment]
Please don't merge it yet. I'd like to take a few cracks at it today.

**Comment by timoxley** [comment]
> I'm not a huge fan of memo, especially as a rescue

@mondoreale  Yep agreed, and your fix looks better if it works, the memo fix is definitely a hack and shouldn't be used like that, especially without a comment to explain. Can you work your fix into this branch?

**Comment by timoxley** [comment]
@juhah updated to make dropdowns more consistent in firefox.

**Comment by mondoreale** [comment]
@timoxley, I'm working my fix into this branch, FYI.

**Comment by mondoreale** [comment]
@timoxley @juhah, I rebased it on `development`, reverted `memo` stuff and applied my fix. Can you guys confirm it works on your end, too? Let's merge it after either of you guys confirms that. 💪 Thanks!

**Comment by juhah** [comment]
@mondoreale I think you're fix got lost... seems like the `memo` is still there?

**Comment by mondoreale** [comment]
@juhah looks like some ping-ponging happened here. I rebased on `development`, then I guess @timoxley force-pushed another rebase yesterday reseting mine (?). I pushed again just now. It's on top of `development`.

@timoxley hope I haven't overwritten anything of yours.

**Comment by mondoreale** [comment]
@timoxley I'm sure I haven't missed anything. Just diff-ed it! 💪

**Comment by mondoreale** [comment]
@juhah, thanks for taking a look. I'll merge this. I'm updating flow in another branch right this second!

**Pull request merged**
