### PR TITLE
[PLATFORM-550] Tablet Views Core Pages Styling Pass

### PR DESCRIPTION
**Pull request by fonty1**
**PR URL:** dwm4cxfqs250g.cloudfront.net

**Jira ticket w/images:**
https://streamr.atlassian.net/secure/RapidBoard.jspa?rapidView=23&modal=detail&selectedIssue=PLATFORM-550

**Tablet > Global**
- Layout:Please move the menu to right that give it more space.
- Button: Please change to SAVE "&" EXIT

**Tablet > Core app view**
- We are not gonna have buttons for create canvas or stream, Dashboard.
- Make a space shorter between Canvases, streams, dashboards, products, purchases, Transactions to fits everything on the page.(Currently "transactions" is chopped)
- Empty page: there is white space in the bottom of page. **_Couldn't replicate_**
- Stream view Implement: Stream view on tablet will be simpler than desktop view.

**Tablet > Profile Setting view**
- Change Password modal: Please move the modal up to user can tap the "SAVE" button more easilyAlso, input field line seems longer, in design line width is 384px and text size is 16pt/24line 
- Timezone selection dropdown box: you can see API Credentials field covers on the dropdown box

**Tablet > Stream details view**
- Menu: Listed all but "Configure, API Access, Historical Data" should be disable Abstract link
- Button: On the tablet view, stream detail isn't editable. Save & Exit is not suitable.Current: Save and ExitImproved: DONE

**Also included...**
- Streams list is now the default `u/`route and appears leftmost in the tabs.
- Profile page cancel redirects to Streams List now.
- There was also a lot of low hanging fruit for Core Pages mobile resolution improvements so I went ahead and added those. Changing the active tab to be left most in mobile was a bit more involved so I left it out. 

**_Note, these will be addressed in the Avatar PR shortly:_**
- Avatar upload: module text changeCurrent text: Drag & drop to upload a cover image or click to browse for oneImproved text : Tap to take a photo or browse for one Abstract link
- Avatar preview modal: It'll be removed
- Avatar update: Currently when I update the avatar, first modal is image of current avatar, when I tap it, translucent text appear. But would be make sense that message appear on first place.

### CODE REVIEW

**Comment by mattatgit** [comment]
@fonty1 Thanks sir, will take a bit of time to go through, so will review first thing monday / once it has a PR URL

**Comment by fonty1** [comment]
It appears as though the PR build environment broke.. I've restarted the build so with some luck its ready tomorrow @mattatgit

**Comment by fonty1** [comment]
@juhah @mattatgit 
PR URL: dwm4cxfqs250g.cloudfront.net

**Comment by mattatgit** [comment]
@fonty1 cheers. @Saorikaji2 Let's look at this tomorrow.

**Comment by fonty1** [comment]
> Looking good 👍 I found only in Stream details view that clicking on disabled links (eg. "Configure") adds the fragment to url ("#configure").
> 
> Also, the notification after saving profile is a bit clunky "Setting has been saved".

Thanks those have been addressed now. Also added signed at the source icons for desktop and your timezone fix for tablet.

I'll merge this @mattatgit because there's hassle in keeping this open with competing changes in different PRs causing conflicts. So it will be on staging.streamr.com shortly.

**Comment by mattatgit** [comment]
@fonty1 Sure, no worries. It just took us a while to put it all together. Feedback is gathered here
https://streamr.atlassian.net/browse/PLATFORM-671

**Pull request merged**
