### PR TITLE
[PLATFORM-1143] Style live preview for stream editor

### PR DESCRIPTION
**Pull request by tumppi**
Live preview for stream editor is now styled according to design:

https://share.goabstract.com/47f70c6d-a1ad-44b6-b941-e24d1efe5b18?mode=build&sha=8b0bd88fa4a5781f3120beb9e6b7754b6a4245ab

### CODE REVIEW

**Comment by fonty1** [comment]
A few v.minor things:
Cell padding (implemented is top): 
Screenshot 2019-11-29 at 15 54 03

Mobile nav:
Screenshot 2019-11-29 at 15 55 16

Preview w/data text & style (implemented is top):
Screenshot 2019-11-29 at 15 54 45

Preview without data text & style (implemented is top):
Screenshot 2019-11-29 at 16 03 24

**Comment by juhah** [comment]
Now that the buttons are in the bottom, maybe the preview should open full height (once data arrives)? If there is less than than 10 entries the buttons get pushed down when then data comes in. It's an edge case if the stream doesn't have previous data. Ping also @mattatgit

**Comment by mattatgit** [comment]
@fonty1 Just wondering what the carousel indicator (two dots, one filled, one not) that is shown in the mobile nav ? Doesn't seem to be part of any designs we've done.

**Comment by mattatgit** [comment]
Bit hard to see what is going here clearly tbh. Any chance we get either get a PR link to play with it or gifs of it in operation ? Ideally what we'd also need is an actual stream we can add ourselves in order to test with.  @tumppi

**Comment by fonty1** [comment]
> @tumppi Just wondering what the carousel indicator (two dots, one filled, one not) that is shown in the mobile nav ? Doesn't seem to be part of any designs we've done.

@mattatgit I can answer this one, it was part of the old designs (https://share.goabstract.com/78f7dfcc-8861-4140-a872-a0cf8b326f99?mode=design&sha=d26401c579383adbf59110e1ed8559ed3fe3ef68)

We reuse this component in the stream editor and the product page stream preview.

**Comment by tumppi** [comment]
I fixed cell padding and mobile nav. I'll go through text content in another PR so that'll be fixed later.

The PR environment is a bit wonky at the moment so this cannot be properly tested there. We agreed with Matt that I'll merge this to development and we'll do another pass on this when tested on staging.

**Pull request merged**
