### PR TITLE
[PLATFORM-1330] Fix price conversion in SetPrice component + specs

### PR DESCRIPTION
**Pull request by mondoreale**
In this PR when "Fix price in fiat" is enabled `priceCurrency` turns into $ and `pricePerSecond` represents $ not DATA. Previously it was \*always\* converted to DATA thus "fixed" was quite loose.

Wrote a buncha specs for it. Hope they're any good (lmk!)

—

_Post-feedback TODO_
- [x] Retain selected currency after switching back from the preview (← @juhah)
- [x] Update styling for the converted amount field (the read-only one) (← @fonty1)
- [x] Convert on change, not on blur (← @fonty1)

### CODE REVIEW

**Comment by fonty1** [comment]
Works well, good hustle!

Some minor UX wins:
- The second input is read only, but doesn't have the disabled styling (I think it's just a subtle greying of the text). 
- It might also be a bit nicer to have the DATA/USD conversion to update `onChange`, rather than `onBlur` for this specific case - it's how it works in the old(prod) price editor works.  Not sure how much trouble that would be though. Just a nice to have IMO.

**Comment by mondoreale** [comment]
Putting me to work, eh? 😅 Anyways, thanks for your feedback. Good notes! I'll include them in this PR.

**Comment by mondoreale** [comment]
@fonty1 

- I made the second field read only, not disabled. You can click-to-select and tab through it. The design doesn't render this field as dimmed out. See feb95a53ef03bbbfadfcf976229a8fe2bf09ceec.
- In 52aa02a68a8c4fec2a342f213af60e3e91382599 I switch from using `onBlur` (via `onCommit`) to `onChange`. Pretty simple.

@juhah in db4ecb70068e40ece99985ac9c16fb62687b61ec I added `preferredCurrency` to `EditControllerContext`. What do you think about this approach?

Cheers guys!

**Comment by mondoreale** [comment]
@fonty1 `type="number"` blocks letters in Chrome but it doesn't in Firefox. Looks like the idea is that if you block some characters then certain type of users may think their keyboards are jammed or something. I don't wanna go against the current with this one.

If we really wanna force it tho we could build some logic around `keypress` event. I'm mentioning it not because I wanna do it (heh) but because I found an interesting future deprecation that can steal your attention for a second:

Screenshot 2020-04-15 10 07 44

PS. `beforeinput` is far from being widely (and correctly) supported but it does sound cool.

**Comment by fonty1** [comment]
> @fonty1 `type="number"` blocks letters in Chrome but it doesn't in Firefox. Looks like the idea is that if you block some characters then certain type of users may think their keyboards are jammed or something. I don't wanna go against the current with this one.
> 
> If we really wanna force it tho we could build some logic around `keypress` event. I'm mentioning it not because I wanna do it (heh) but because I found an interesting future deprecation that can steal your attention for a second:
> 
> Screenshot 2020-04-15 10 07 44
> 
> PS. `beforeinput` is far from being widely (and correctly) supported but it does sound cool.

@mondoreale damn those keyboard jamming complainers! 😂 
All g, maybe we can trust people will type numbers in there all the same.

**Pull request merged**
