### PR TITLE
[PLATFORM-1273] Simulate production conditions for review 

### PR DESCRIPTION
**Pull request by fonty1**
Remove the PR build `DATA_UNIONS` flag with the goal to give Matt an opportunity to approve the upcoming changes about to land in production when the `NEW_MP_CONTRACT` flag is on and `DATA_UNIONS` is off.

I don't think this needs to be merged.

### CODE REVIEW

**Comment by fonty1** [comment]
@mattatgit if you checkout the PR url:
http://streamr-marketplace-pr-d392dcfceff01cfe59613bab52fac14a49e393dc.s3-website-eu-west-1.amazonaws.com/

This is meant to be an accurate copy of how production will behave when uniswap is released:
- Creating a product goes directly to the new product editor. 
- New product page
- Purchase modal includes ETH and DAI

Product to test with:
http://streamr-marketplace-pr-d392dcfceff01cfe59613bab52fac14a49e393dc.s3-website-eu-west-1.amazonaws.com/marketplace/products/86266e699c2c4f348ad7314bfccf51d300bfa6f969a14af4b2d7659b970764d8

**Comment by mattatgit** [comment]
@fonty1 thanks! Is the goal to release it this week, or can it wait till next ? If next, we'll be back at work & can test it properly rather than trying to squeeze it in during holidays.

**Comment by fonty1** [comment]
@mattatgit I've got confirmation that this can wait till next week. By then the PR build might have expired, so just poke me to redeploy if that happens.

**Comment by mattatgit** [comment]
@fonty1 Ok, great, thanks. Will check it out first thing next week.

**Comment by mattatgit** [comment]
@fonty1 
Haven't been able to test it fully yet, will get to it as soon as i can, but one thing that needs a tweak is that the dropdown style has icons & text on opposite sides to the design.

Abstract link to component style
https://share.goabstract.com/9714384e-bcd8-43fc-95bf-792c7ff6e23d?mode=design&sha=87fe4acd54bce2de256d066db8d44604d58a36d5

Screenshot 2020-02-24 15 18 57

**Comment by mattatgit** [comment]
Seems like the horizontal rule above the action buttons is missing too.

Screenshot 2020-02-24 15 38 19

**Comment by fonty1** [comment]
Thanks @mattatgit - I've updated the select boxes to be as designed now across the app (in PR stage) and added that bottom border.

Once that's merged I'll update this branch with a new link for review.

**Comment by mattatgit** [comment]
@fonty1 Ok, thank you sir. Once we get the new link we'll resume testing it.

**Comment by mattatgit** [comment]
@fonty1 Also, any reason for changing the title of this step in the payment modal from "Choose access period & payment token" to "Choose your access period" ? First one is more accurate, so just wondering if that was oversight or intended improvement ?

**Comment by mattatgit** [comment]
@fonty1  Another thing, Henri asked me to add Uniswap branding back into the purchase flow (it was there at one point.) Have dropped it back in, screenshot is below, and abstract link is

https://share.goabstract.com/ab570a5c-85ee-4a5f-a7ca-8bec371606c7?mode=design&sha=b604ed589b5c7c197ba0ced1e3b9d94ab93da13d

Can make this into a Jira ticket instead if you'd prefer, just let me know.
Screenshot 2020-02-26 11 20 03

**Comment by fonty1** [comment]
> @fonty1 Also, any reason for changing the title of this step in the payment modal from "Choose access period & payment token" to "Choose your access period" ? First one is more accurate, so just wondering if that was oversight or intended improvement ?

There was a bug in recognising whether the user was on mobile or desktop, so it was showing the mobile version on desktop, which has the shortened title "Choose your access period". 

Mobile:
https://share.goabstract.com/ba43c054-c900-4909-9deb-fdd1c913464a?mode=design&sha=7a8799045078d26e1fc7092335833cdbad038723

**Comment by mattatgit** [comment]
@fonty1 Ok, got it, thanks.

**Comment by fonty1** [comment]
@mattatgit, close your eyes and get ready to enter a simulation where the marketplace is upgraded, but data unions are hidden. Good luck!

http://streamr-marketplace-pr-ab4480536614e7e99015510f41a0ea6695412c14.s3-website-eu-west-1.amazonaws.com/marketplace/products/86266e699c2c4f348ad7314bfccf51d300bfa6f969a14af4b2d7659b970764d8

**Comment by mattatgit** [comment]
@fonty1 Thank you sir, will check it out & get back to you

**Comment by mattatgit** [comment]
@fonty1 
I assume the test product should show up in my Purchases ? (assuming i have connected the purchasing eth address + my Streamr account, which i have). Doesn't seem to be doing that.

**Comment by mattatgit** [comment]
Have created one ticket about the error handling issues, specifically for free <> paid product switching but i guess it might apply to other areas too. Will have to test it some more.

https://streamr.atlassian.net/browse/PLATFORM-1293

Question is: what is to be tested exactly for this PR ? This error handling stuff should probably be handled in another PR & make this one specifically about Uniswap perhaps ?

**Comment by fonty1** [comment]
> @fonty1
> I assume the test product should show up in my Purchases ? (assuming i have connected the purchasing eth address + my Streamr account, which i have). Doesn't seem to be doing that.
> Transaction also not showing up in my Transactions tab, so looks like something to do with the account connection.

@mattatgit I just tried myself and it looks like there's some problems with the watcher or database, which could interfere with it. The contract has been updated a bunch of times so the environments I guess are unstable. I'll ping Santos about that and let you know when I can do those same steps. 

To be safe/clean: 
- create a new product, 
- confirm it exists on the marketplace, 
- logout, 
- create a new metamask ethereum account/address, 
- transfer some coin to it internally in metamask, 
- log-in/authenticate with it, 
- purchase that product

**Comment by fonty1** [comment]
> Question is: what is to be tested exactly for this PR ? This error handling stuff should probably be handled in another PR & make this one specifically about Uniswap perhaps ?

All the Uniswap stuff has been merged already (inc error handling), and inserted into this PR build. This PR build is designed to simulate a release to production that contains:

- new product page,
- new product page editor/creator,
- uniswap payments
- any other minor things we've been working on, on the other core pages, 

But **without Data Unions**. E.g. "Create" leads to the Data Product creator, rather than the choice modal. Purpose of this was so we could release the above, before we are ready to release DUs.

**Comment by mattatgit** [comment]
@fonty1 Thanks for clarifying! Very helpful. Ok, so we need to test a bit more & fill in some blanks where there was perhaps a bit of missing design eg around the error handling / validation of the create flow, so  we'll do that & then get back to you as soon as we can, probably early-mid next week.

**Comment by fonty1** [comment]
@mattatgit - the watcher issue resolved, I was able to create, purchase using Uniswap, and observe the purchase in 'my purchases'. You can create a new product or use this one:

http://streamr-marketplace-pr-99e134b79c07af336a7b5ecccfb62c51090f838b.s3-website-eu-west-1.amazonaws.com/marketplace/products/048413d3d5ab4132adfd690527023e8fa2bdb5685a9642c3b140a46a381d2e67

**Comment by mattatgit** [comment]
@fonty1 Ok yep, products are showing up in my Purchases now, thnx

**Comment by mattatgit** [comment]
Or should i say "Mr Funtana"

**Comment by fonty1** [comment]
> Or should i say "Mr Funtana"

It's a typo that stuck 😄

**Pull request closed without merging**
