### PR TITLE
[PLATFORM-990] Minimal embeds canvases

### PR DESCRIPTION
**Pull request by timoxley**
Prevents edits, hides nav & toolbar in embed mode.
Fixes generated embed code.
Prevents redirecting to login for embed urls.

To test:
* Share a canvas publicly.
* Get embed code.
* Access the url in embed code directly while logged in & logged out (i.e. incognito mode). e.g. http://localhost/canvas/embed/sUc-jCKxSKaVx4KFJGZ75wjOTJOzEfTnWFwiJJRRsgEA
* Drop embed code iframe on a docs page, access docs page see iframe works logged in & logged out.

~~*update*: Just noticed running canvases have a recursive loop issue if user is logged out.~~ Fixed

### CODE REVIEW

**Comment by juhah** [comment]
Looks pretty good already!

Quick testing notes:

- Menu is missing from normal Editor view
- Scrolling weirdness in iframe when moving modules around
- I did not see any data flowing when viewing public canvas if logged out (or viewing incognito)
- Accessing a private canvas redirects to login, perhaps it should just show an error?

**Comment by timoxley** [comment]
@juhah fixed missing navbar, fixed data flowing for running logged in/out canvases.

> Scrolling weirdness in iframe when moving modules around

I'll try fix this when I fix zoom, same issue when moving modules around normal canvas editor, just less noticeable as area is larger.

**Comment by timoxley** [comment]
> Accessing a private canvas redirects to login, perhaps it should just show an error?

yes perhaps.

**Comment by timoxley** [comment]
Merging for now, can address embed-specific error handling later.

**Pull request merged**
