### PR TITLE
[PLATFORM-585][PLATFORM-538] Fix select's (port value) placeholder

### PR DESCRIPTION
**Pull request by mondoreale**
~I've used solution suggested by @juhah here!~ It fixes preselecting the valueless option that acts as a placeholder.

### CODE REVIEW

**Comment by timoxley** [comment]
I wonder if this will cause server-side validation issues

**Comment by mondoreale** [comment]
Interesting. It's not "perfect" (read: explodes 💥). Still on it.

**Comment by mondoreale** [comment]
`<select>` doesn't like `null` values, fyi.

**Comment by mondoreale** [comment]
@timoxley @juhah this is the most "local" fix I could come up with. It's just for preselection.

**Pull request merged**
