### PR TITLE
[PLATFORM-564] Custom logo link on the Editor page

### PR DESCRIPTION
**Pull request by mondoreale**
The logo in the top left corner is gonna link to `routes.canvases()` on the Editor page. Everywhere else it links to ~~`routes.root()`~~ `process.env.PLATFORM_ORIGIN_URL`.

~~Conflicts with changes from #475.~~

---

[PLATFORM-564](https://streamr.atlassian.net/browse/PLATFORM-564) 🚀

### CODE REVIEW

**Comment by mondoreale** [comment]
@fonty1 let me fix the conflict real quick.

**Comment by mondoreale** [comment]
Nice thing here is that `Nav` and `MobileNav` use the same `LogoItem` now.

**Comment by fonty1** [comment]
LGTM but I'm not sure the ticket is valid - see the discussion in the comments. 

> I recommend we make a new ticket about keyboard navigation, and keep this ticket about the Streamr logo link, which feels like an easy win. I agree it should take to the base (root) url - which displays the landing page if it is deployed, and if not, it would reach the Core app router which would display the default page (streams).

Maybe @mattatgit can confirm this- If the spirit of the ticket is no longer valid, please update the ticket description or close the ticket to avoid any unnecessary keyboard tapping :)

**Comment by mattatgit** [comment]
@fonty1 @mondoreale You're right. Sorry if this got lost in translation, but the final decision was the have the logo linking back to the public site top page.

**Comment by mondoreale** [comment]
Omg, I've scanned through the conversation but missed that part, apparently. Closing it.

**Comment by mondoreale** [comment]
Extracted ba03ee4a46b19bcdf64fdcb4bdf560c0c4ec3c9c from this PR and pushed to `development`, FYI.

**Pull request closed without merging**
