### PR TITLE
[PLATFORM-506] Updated core app nav

### PR DESCRIPTION
**Pull request by mondoreale**
@mattatgit here's the new "core" dropdown:

Screenshot 2019-05-06 15 20 46

And here, the new dropdown attached to the avatar:

Screenshot 2019-05-06 15 21 10

Navigation on small screens needs a sepatate update. Looks like there are some features missing tho. And the nav, in general, could use some small refactoring. Tried to keep the changes at minimum for this round!

And for the mobile nav, for now I simply applied the same set of "core" links:

Screenshot 2019-05-06 15 32 12

### CODE REVIEW

**Comment by mondoreale** [comment]
There's an outstanding issue with tablet nav here (bar height & logo size). Will address tomorrow.

**Comment by fonty1** [comment]
@mondoreale there's a few things I noticed from:
https://share.goabstract.com/423d29a5-a158-45be-9d0d-7fcf0b509680?mode=build&sha=4860508c027e5c5e6ed406f2ff98d6cadd6e7119

- Docs nav menu absent
- Menu hover state doesn't seem right
- Vertical spacing between menu elements seems a little tight?

Doesn't look like those tasks are in the Jira ticket though so perhaps @mattatgit knows more about this.

**Comment by mondoreale** [comment]
@fonty1 good notes! 🙌  I'll look at it again in the am, tomorrow.

**Comment by mattatgit** [comment]
@mondoreale Looking pretty good though @fonty1 's notes are good, all three points are correct there. Will get @Saorikaji2 to comment too, just in case, as this navbar is more her bag than mine, and she might have more notes.

**Comment by Saorikaji2** [comment]
Yes, Mr Fontana’s points are good. I am also concerned about the blank avatar icon’s line weight — seems slightly thinner than design (which is 1px). Here is the [Abstract link](https://share.goabstract.com/e4c1ffe5-266f-4771-a008-21b27564a8d2?mode=design&sha=fd405e37868d9b85a5d9e33595fd9c308f0ff45a).
Empty Avatar


Dropdown vertical spacing is
Font size 12
Character space : 2
Line space : 28

Drop down

**Comment by fonty1** [comment]
@Saorikaji2 should an empty avatar be the initials of the user or the empty profile img?

**Comment by mattatgit** [comment]
@fonty1 It should be the initials of the user by default, unless the user has not entered them. It should only show this blank avatar if the user has not entered any name (possible at the moment for ethereum ID users)

**Comment by mattatgit** [comment]
@juhah @mondoreale yeah probably Canvases should be first. ie it should reflect the tab order in Core app. Reason for this is that Henri & I discussed putting streams first ie on far left of Core, as first / default tab, but we haven't implemented this yet. Shouldn't be too hard to do, but haven't done it yet.

**Comment by fonty1** [comment]
> @juhah @mondoreale yeah probably Canvases should be first. ie it should reflect the tab order in Core app. Reason for this is that Henri & I discussed putting streams first ie on far left of Core, as first / default tab, but we haven't implemented this yet. Shouldn't be too hard to do, but haven't done it yet.

In a separate PR yet to be merged, Streams is the first tab of the Core Pages so probably should be the first option here too. I will show you the PR URL in one moment.

**Comment by mondoreale** [comment]
I'm still addressing the issues, guys. The avatar is on my radar. Taking care of it in this iteration. Will have a better update for you tomorrow. It's gonna be awesome.

**Comment by mattatgit** [comment]
Yep, let's just get it in please, even if not yet perfect. I have to demo this tomorrow internally & it can't really be demoed without the correct navbar in there.

**Comment by mondoreale** [comment]
Core menu / desktop

Screenshot 2019-05-08 21 40 14

Core menu / tablet

Screenshot 2019-05-08 21 42 08

"Avatar" dropdown / desktop

Screenshot 2019-05-08 21 45 47

"Avatar" dropdown / tablet

Screenshot 2019-05-08 21 43 20

—

And this is a rough update of the navigation on mobile

Screenshot 2019-05-08 21 46 30

It's kinda temporary but I had to do it. It's all a refactored version of the previous navigation. Comes with a whole bunch of updated! @Saorikaji2 @mattatgit hopefully I managed to wrap all your thoughts into it at this point.

There's 1 missing part. We don't highlights currently active dropdown toggle (darker "CORE" color). We don't have a proper setup for it. I left them links in their default "unselected" form.

**Comment by mondoreale** [comment]
@juhah the scroll issue is outside of the scope of this ticket. Tried it and it seems that you're referring to "Cancel / Save and exit" nav bar. It's a different component. Has to be refactored in a similar manner to what happened to the top nav just now.

**Comment by mondoreale** [comment]
Forgot to push…

It's a decent and quite big change, after all. My initial intention was to keep it as small as possible. Welp…

The complexity of the top navigation component has been bothering me for quite some time now. We (I) mixed mobile and desktop/tablet navigation together even tho they're completely different, and it ended up being an impossible-to-maintain mess.

Now desktop/tablet navigation is 1 thing – `$shared/components/Nav`, and mobile naviagtion is another thing – `$shared/components/MobileNav`. Both have different structures w/ only things they actually need. It's very hard to make everyone happy and some navigations aren't meant to be together, as one.

We do have a bunch of changes for the mobile nav coming, as far as I can tell. This will make it easier!

What's also important, and something I wanted to make happen for a long time is that both (!) navs, which just few extra mods, can become contextual. The frame is fairly robust. We wouldn't have to deal with "Cancel / Save and exit" navs separately. It could all be packed withing the nav, or better!, it could be told to display other stuff coming from elsewhere.

Enough talking.

**Comment by mondoreale** [comment]
@fonty1 have a look at my `Avatar` and `Initials` components. I saw your recent mods in that area. in one of the upcoming iterations I'mma try to squish them together.

**Comment by mondoreale** [comment]
Spotted an issue in "Core menu / tablet" I posted above. Fixing.

**Comment by mondoreale** [comment]
Ok. Fixed.

Screenshot 2019-05-08 22 42 10

**Pull request merged**
