### PR TITLE
Update flow to 0.113.0 (latest)

### PR DESCRIPTION
**Pull request by mondoreale**
You guys are gonna love it! 😅 

Please remember to
- reinstall "global" flow-bin in your systems, and
- `npm ci`.

Throw an eye. Let me know what you think.

### CODE REVIEW

**Comment by timoxley** [comment]
Hm, so moving props to the start changes the meaning subtly, it prevents props from overriding attributes set as defaults. Many components may not use this feature but I'm pretty sure there are some that do, did you check for that?

**Comment by mondoreale** [comment]
**tl;dr** yes, I did.

@timoxley, you're on point, and for the record, I did go through most of the components I modified. I looked up how are they used, what props are they receiving, etc. I'm quite sure I didn't break anything by accident here. :)

What I did notice is that some components allow you to push `className` to them to overwrite component's internal `className`. I kept that logic whenever I spotted it.

Having said that, still, if you notice anything suspicious ping me and I'll look into it.

**Comment by mondoreale** [comment]
I've gone through another round here, tweaked some changes, discarded some. I'm gonna update a couple of more flow-related packaged in this PR as well as get rid of all unncessary `$FlowFixMe`s. Cheers!

**Comment by mondoreale** [comment]
Alright, this one seems to be fairly harmless to merge. Guys, see any blockers here?

**Comment by mondoreale** [comment]
Also, I'm addressing other package updates in a separate PR (coming up shortly). And another one for `$FlowFixMe`. All for the sake of making it easier to read. That's quite a lot of changes.

**Comment by mondoreale** [comment]
I'll merge in a minute, or 2. Getting there! Thanks guys!

**Comment by mondoreale** [comment]
@timoxley, about the global one, yes, apparently mind doesn't know… gotta fix it.

**Pull request merged**
