### PR TITLE
[PLATFORM-1232] Update styling for the auth pages

### PR DESCRIPTION
**Pull request by mondoreale**
Looks like this is all it takes! 💪

### CODE REVIEW

**Comment by mondoreale** [comment]
@fonty1 it's a very small one, I promise! 😉

**Comment by fonty1** [comment]
Can probs delete this too from the en.po

msgid "general##footnote"
msgstr "Made with ❤️ & ☕ by Streamr contributors in 2019"

**Comment by mondoreale** [comment]
Thanks @fonty1! 🤝 

The text change… were you talking about "Authenticate with ethereum"?

**Comment by fonty1** [comment]
> Thanks @fonty1! 🤝
> 
> The text change… were you talking about "Authenticate with ethereum"?

Yep 👍

**Pull request merged**
