### PR TITLE
[PLATFORM-444] Finalize Avatar

### PR DESCRIPTION
**Pull request by fonty1**
This component was built without the makeup of the final end component so it required some refactoring to get the image upload in the right format.

Also includes the design request to remove the Preview step.

Also included is the navbar & userpages Avatar Circle styles.

~I'm not 100% sure this is working because there is an issue on the S3 bucket:
https://streamr.atlassian.net/browse/DEVOPS-39~ Issue resolved. 

Test PR URL (valid till approx May 5th~):
https://d1zdxf74ngsf3y.cloudfront.net

### CODE REVIEW

**Comment by mattatgit** [comment]
@juhah Be good to get this one in, its been sitting there for nearly a month

**Comment by mattatgit** [comment]
@fonty1 This is what the edit profile section looks like in Safari when i load the test PR link.
Edit_profile_layout

**Comment by mattatgit** [comment]
@fonty1 Also avatars are very low res in this PR test url. But i guess that is fixed by CORE-1700

**Comment by juhah** [comment]
Code looks fine by me but I'm just unable to test it.

**Comment by fonty1** [comment]
I will merge this for a better opportunity to test. If all goes well the Avatar upload should be working in staging.streamr.com in an hour or two.

**Pull request merged**
