### PR TITLE
[FRONT-309] Upgrade to streamr-client version 5.0.0-beta.10, fix DU 2.0 deploy

### PR DESCRIPTION
**Pull request by juhah**
Upgrade to `streamr-client` version `5.0.0-beta.10`. Also added new build variable for sidechain `chainId` that gets passed along to client.

### CODE REVIEW

**Review by hpihkala — COMMENTED** [review]
@juhah Otherwise looks good to me, but I was expecting to see some changes related to `getAddress()` becoming `async`. Is that method never called by the frontend?

**Comment by juhah** [comment]
> Is that method never called by the frontend?

Yes, `client.getAddress()` is not used.

**Review by hpihkala — APPROVED** [review]
Okay, thanks for confirming! (note failing tests though)

**Comment by juhah** [comment]
storybook build is now failing, investigating

**Pull request merged**
