### PR TITLE
[PLATFORM-1081] Fix code editor text focus bug 

### PR DESCRIPTION
**Pull request by timoxley**
Clicking the title to focus the editor was losing the editor focus immediately after setting it. Oops.

#### To Test

1. Add Java Module
2. Edit Code
3. Click canvas background to ensure code editor is not focussed.
4. Click Code Editor title bar
5. Focus should be in the code editor, you should be able to type to change code content

### CODE REVIEW

**Comment by juhah** [comment]
The described case works ok. As the editor window can't be moved, should we remove the hand cursor? Also, if you have two editors open, it should probably bring the selected module's editor to the top.

Found this bug as well (not sure if regression here from or base branch):
- Add Java module, edit code so that there is an error and hit apply
- Close editor
- Add SolidityCompileDeploy, wait for autosave (module will "nudge" a bit)
- Open editor -> Solidity module will crash

ezgif-2-72a3f712331a

**Comment by timoxley** [comment]
> Found this bug as well 

@juhah appears to be a backend bug, have created a ticket https://streamr.atlassian.net/browse/CORE-1817

**Comment by timoxley** [comment]
@mondoreale @juhah drag/drop fixed by changing title -> editor focus handler to use click event instead of mousedown in cb927eb1d

**Comment by timoxley** [comment]
> Works well now. As the module of the selected editor is highlighted, would be nice to have the opposite as well, ie. bring the editor of the selected module on top.

@juhah looked into this, wasn't totally straightforward. TODO later.

**Pull request merged**
