### PR TITLE
[PLATFORM-647] Swap user id and name

### PR DESCRIPTION
**Pull request by mondoreale**
Didn't notice that [`PLATFORM-647`](https://streamr.atlassian.net/browse/PLATFORM-647) is more of an idea. Anyway, materialized it. @mattatgit, thoughts?

Screenshot 2020-01-23 14 53 20

### CODE REVIEW

**Comment by mattatgit** [comment]
@mondoreale I think it's maybe a good quick fix for now. The share dialogue is being completely reworked atm by @timoxley & will return as a modal sidebar, giving lots more room to add people & handle other stuff.

So i'd be fine to have this in there until the new stuff comes out.

My only comments would be:
*  the label for the input field should be "Email or ETH address"
* placeholder text should have some padding between start of field & first letters. Generally we used 16px (i think)
* placeholder text should not have a period "." at end of text
* placeholder text should be "Enter your email or ETH address"

**Comment by mondoreale** [comment]
All of your points are already implemented in #846. Merging this one now, and the other one shortly!

**Comment by juhah** [comment]
@mondoreale Tests seem to be breaking after these changes

**Comment by mondoreale** [comment]
I must’ve missed them. Will fix tonight! Sorry for the blockage. — MR

W dniu wt., 28.01.2020 o 12:25 juhah <notifications@github.com> napisał(a):

**Comment by mondoreale** [comment]
@juhah just pushed a fix, see 4cddd8c46f6f611938db9f9c7cfd28e572447529.

**Pull request merged**
