### PR TITLE
[PLATFORM-606] Add action to refresh stream

### PR DESCRIPTION
**Pull request by juhah**
Adds an action to refresh stream from meatball menu.

### CODE REVIEW

**Comment by mattatgit** [comment]
@fonty1 Yeah, probably good to have if there are no other visible confirmations for the user

**Comment by juhah** [comment]
@mattatgit Added notifications after copy and stream refresh.

Screen Shot 2019-05-10 at 9 57 26
Screen Shot 2019-05-10 at 9 57 19
Screen Shot 2019-05-10 at 10 01 06 1

**Comment by mattatgit** [comment]
@juhah would be good to update the purple triangle with the orange icon that we replaced it with

Screenshot 2019-05-10 17 52 02

Abstract
https://share.goabstract.com/c442fc5d-5ac2-4fb4-94ea-0ae99bfb86d0?mode=design&sha=4860508c027e5c5e6ed406f2ff98d6cadd6e7119

**Comment by juhah** [comment]
@mattatgit @timoxley that could be included in #414 with other notificartion updates

**Pull request merged**
