### PR TITLE
Update streamr-client to ^2.2.5.

### PR DESCRIPTION
**Pull request by timoxley**
Old client no longer seems to work, any subscriptions with resends don't flow. Sometimes backend requests seem to never respond, which would be consistent with the tests that seem to be timing out inconsistently & intermittently.

This at least makes canvases work *sometimes*.

### CODE REVIEW

**Comment by fonty1** [comment]
I couldn't get much to work, running latest docker, i.e. 
`docker pull streamr/tracker:dev && docker pull streamr/broker-node:dev && docker pull streamr/engine-and-editor:dev && streamr-docker-dev start 5`

Clock to Table test works sometimes. I couldn't get `sendToStream` to work at all.

**Comment by timoxley** [comment]
@fonty1 yeah I think you need to wipe your docker environment to get it to work.

**Comment by fonty1** [comment]
Ah, could be a separate bug then- restarting a canvas seems to stop pushing events to a table:
table

**Comment by timoxley** [comment]
> restarting a canvas seems to stop pushing events to a table:

Did you reset your docker env? I was seeing that before, but not now.

**Comment by fonty1** [comment]
> > restarting a canvas seems to stop pushing events to a table:
> 
> @fonty1 Did you reset your docker env? I was seeing that before, but not now.
> 
> ```
> docker system prune -a --volumes
> ```

Yep, I did exactly that, I will triple check now though

**Comment by fonty1** [comment]
Yep, pretty odd, after:
```
docker system prune -a --volumes
docker pull streamr/tracker:dev && docker pull streamr/broker-node:dev && docker pull streamr/engine-and-editor:dev && streamr-docker-dev start 5
```
Still get this:
tableweird

**Comment by timoxley** [comment]
I think the bug may be unrelated to this, there's similar but not exact issues in production.

**Pull request merged**
