### PR TITLE
Update streamr-client to 2.2.2

### PR DESCRIPTION
**Pull request by timoxley**
* `streamr-client` now doesn't like an empty object as a `resend` option, fixed in https://github.com/streamr-dev/streamr-platform/commit/7019d83b1402d55c85af6cb60bfa88a73fda934c. This was causing: https://github.com/streamr-dev/streamr-platform/pull/711#discussion_r334790721  Screenshot 2019-10-15 at 10 29 23
* Had to increase timeout on some tests, probably not a good sign. Timeout increase was only needed with `streamr-client@2.2.2`, prior versions e.g. `2.2.1` have no issues. The [diff between `2.2.1` and `2.2.2`](https://github.com/streamr-dev/streamr-client-javascript/compare/e479b68927b8c6c5ce5d4fea8e8eb4309e55e9ec...7cb6790e2f53b984a2d8aa191ddda13f0df03b39#diff-b33004f77181ebaafb1f0c41f5c34f07R45-R53) doesn't reveal an obvious cause to me, but I suspect the resend changes might be it.

### CODE REVIEW

**Comment by tumppi** [comment]
Seems like they have upped `STORAGE_DELAY` in `streamr-client` tests from 500 to 2000 so probably related to the resend changes.

**Comment by timoxley** [comment]
@tumppi ahh, great spotting

**Comment by timoxley** [comment]
@tumppi hang on, data doesn't seem to flow when a canvas is stopped then started again. Investigating.

**Comment by timoxley** [comment]
Closing this, `2.2.2` seems to have issues.

**Pull request closed without merging**
